# Generated by Django 6.0 on 2025-12-27 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='أيقونة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('audio_file', models.FileField(upload_to='lessons/audio/', verbose_name='الملف الصوتي')),
                ('transcribed_text', models.TextField(blank=True, null=True, verbose_name='النص المفروغ')),
                ('transcribed_text_reviewed', models.BooleanField(default=False, verbose_name='تمت مراجعة النص')),
                ('duration', models.IntegerField(default=0, verbose_name='المدة بالثواني')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور')], default='draft', max_length=20, verbose_name='الحالة')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='الملخص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.category', verbose_name='التصنيف')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lessons', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('paragraph', 'فقرة'), ('heading', 'عنوان'), ('point', 'نقطة')], default='paragraph', max_length=20, verbose_name='نوع القسم')),
                ('text', models.TextField(verbose_name='النص')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('audio_timestamp', models.FloatField(blank=True, null=True, verbose_name='وقت الصوت بالثواني')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lessons.lesson', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'قسم الدرس',
                'verbose_name_plural': 'أقسام الدروس',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('current_position', models.FloatField(default=0, verbose_name='الموضع الحالي بالثواني')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lessons.lesson', verbose_name='الدرس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقدم الدرس',
                'verbose_name_plural': 'تقدم الدروس',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
