# Generated by Django 6.0 on 2025-12-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'تصنيف (مادة)', 'verbose_name_plural': 'التصنيفات (المواد)'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('subject', 'مادة دراسية'), ('skill', 'مهارة'), ('topic', 'موضوع'), ('level', 'مستوى'), ('other', 'أخرى')], default='subject', max_length=20, verbose_name='نوع التصنيف'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
    ]
