# Generated by Django 6.0 on 2025-12-27 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_category_options_category_category_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['grade__order', 'order', 'name'], 'verbose_name': 'مادة دراسية', 'verbose_name_plural': 'المواد الدراسية'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المادة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.category', verbose_name='المادة الدراسية'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان الدرس'),
        ),
        migrations.AddField(
            model_name='category',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='lessons.grade', verbose_name='الصف الدراسي'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('grade', 'name')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
    ]
