# Generated by Django 6.0 on 2025-12-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_grade_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
