# Generated by Django 6.0 on 2026-01-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/pdf/', verbose_name='ملف PDF'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='محتوى نصي'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='listening_time_seconds',
            field=models.IntegerField(default=0, verbose_name='وقت الاستماع بالثواني'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/audio/', verbose_name='الملف الصوتي'),
        ),
    ]
