# Generated by Django 4.2.27 on 2026-01-13 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0005_lesson_pdf_file_lesson_text_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صحيح/خطأ'), ('open_ended', 'سؤال مفتوح'), ('voice_answer', 'إجابة صوتية')], default='multiple_choice', max_length=20, verbose_name='نوع السؤال')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('points', models.IntegerField(default=1, verbose_name='النقاط')),
                ('correct_answer', models.TextField(blank=True, null=True, verbose_name='الإجابة الصحيحة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان الاختبار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('quiz_type', models.CharField(choices=[('practice', 'تمرين'), ('exam', 'امتحان'), ('quiz', 'اختبار قصير')], default='practice', max_length=20, verbose_name='نوع الاختبار')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='المدة بالدقائق')),
                ('passing_score', models.IntegerField(default=60, verbose_name='نقاط النجاح')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='الحد الأقصى للمحاولات')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('review', 'قيد المراجعة'), ('approved', 'معتمد'), ('published', 'منشور')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lessons.category', verbose_name='المادة الدراسية')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'الاختبارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='محتوى النص'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('timeout', 'انتهى الوقت')], default='in_progress', max_length=20, verbose_name='الحالة')),
                ('score', models.FloatField(default=0, verbose_name='الدرجة')),
                ('total_points', models.IntegerField(default=0, verbose_name='إجمالي النقاط')),
                ('percentage', models.FloatField(default=0, verbose_name='النسبة المئوية')),
                ('passed', models.BooleanField(default=False, verbose_name='ناجح')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بدأ في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='اكتمل في')),
                ('time_taken_minutes', models.IntegerField(default=0, verbose_name='الوقت المستغرق بالدقائق')),
                ('volunteer_feedback', models.TextField(blank=True, null=True, verbose_name='ملاحظات المتطوع')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تمت المراجعة في')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lessons.quiz', verbose_name='الاختبار')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attempts', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محاولة الاختبار',
                'verbose_name_plural': 'محاولات الاختبارات',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_quizzes', to='lessons.lesson', verbose_name='الدرس المرتبط'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة'),
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500, verbose_name='نص الخيار')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lessons.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'خيار السؤال',
                'verbose_name_plural': 'خيارات الأسئلة',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lessons.quiz', verbose_name='الاختبار'),
        ),
        migrations.CreateModel(
            name='VolunteerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reviewer', 'مراجع محتوى'), ('transcriber', 'مفروغ صوتي'), ('quiz_reviewer', 'مراجع اختبارات'), ('content_creator', 'منشئ محتوى'), ('admin', 'مدير')], max_length=30, verbose_name='الدور')),
                ('tasks_completed', models.IntegerField(default=0, verbose_name='المهام المكتملة')),
                ('tasks_in_progress', models.IntegerField(default=0, verbose_name='المهام قيد التنفيذ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تم التعيين في')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='lessons.category', verbose_name='المادة (اختياري)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_roles', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'دور المتطوع',
                'verbose_name_plural': 'أدوار المتطوعين',
                'unique_together': {('user', 'role', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='نص الإجابة')),
                ('answer_audio', models.FileField(blank=True, null=True, upload_to='quizzes/audio_answers/', verbose_name='إجابة صوتية')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة')),
                ('points_earned', models.IntegerField(default=0, verbose_name='النقاط المكتسبة')),
                ('needs_review', models.BooleanField(default=False, verbose_name='يحتاج مراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lessons.quizattempt', verbose_name='المحاولة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lessons.question', verbose_name='السؤال')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lesson_answers', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.questionchoice', verbose_name='الخيار المختار')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
