# Generated by Django 4.2.27 on 2026-01-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_question_quiz_alter_lesson_text_content_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='conversion_error',
            field=models.TextField(blank=True, null=True, verbose_name='خطأ التحويل'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='conversion_progress',
            field=models.IntegerField(default=0, verbose_name='نسبة التقدم (%)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='conversion_status',
            field=models.CharField(choices=[('idle', 'في الانتظار'), ('extracting_text', 'جاري استخراج النص'), ('text_extracted', 'تم استخراج النص'), ('converting_audio', 'جاري تحويل النص إلى صوت'), ('completed', 'اكتمل'), ('failed', 'فشل')], default='idle', max_length=20, verbose_name='حالة التحويل'),
        ),
    ]
