# Generated by Django 6.0 on 2025-12-27 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('audio_file', models.FileField(upload_to='volunteers/audio/', verbose_name='الملف الصوتي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('transcribed', 'تم التفريغ'), ('reviewed', 'تمت المراجعة'), ('published', 'منشور')], default='pending', max_length=20, verbose_name='الحالة')),
                ('transcribed_text', models.TextField(blank=True, null=True, verbose_name='النص المفروغ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL, verbose_name='المسجل')),
            ],
            options={
                'verbose_name': 'تسجيل صوتي',
                'verbose_name_plural': 'التسجيلات الصوتية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_text', models.TextField(verbose_name='النص بعد المراجعة')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='تعليقات')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('needs_revision', 'يحتاج مراجعة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_reviews', to='lessons.lesson', verbose_name='الدرس')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
            ],
            options={
                'verbose_name': 'مراجعة تفريغ',
                'verbose_name_plural': 'مراجعات التفريغ',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
