# Generated by Django 6.0 on 2025-12-27 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صحيح/خطأ'), ('text_answer', 'إجابة نصية'), ('audio_answer', 'إجابة صوتية')], default='multiple_choice', max_length=20, verbose_name='نوع السؤال')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_audio', models.FileField(blank=True, null=True, upload_to='questions/audio/', verbose_name='صوت السؤال')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('points', models.IntegerField(default=1, verbose_name='النقاط')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(verbose_name='نص الخيار')),
                ('is_correct', models.BooleanField(default=False, verbose_name='صحيح')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tests.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'خيار',
                'verbose_name_plural': 'خيارات',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('passing_score', models.IntegerField(default=70, verbose_name='نقاط النجاح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lessons.lesson', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'الاختبارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.quiz', verbose_name='الاختبار'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='النتيجة')),
                ('passed', models.BooleanField(default=False, verbose_name='نجح')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.quiz', verbose_name='الاختبار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محاولة اختبار',
                'verbose_name_plural': 'محاولات الاختبارات',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='الإجابة النصية')),
                ('answer_audio', models.FileField(blank=True, null=True, upload_to='answers/audio/', verbose_name='الإجابة الصوتية')),
                ('is_correct', models.BooleanField(default=False, verbose_name='صحيح')),
                ('points_earned', models.FloatField(default=0, verbose_name='النقاط المكتسبة')),
                ('reviewed', models.BooleanField(default=False, verbose_name='تمت المراجعة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_answers', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.choice', verbose_name='الخيار المختار')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='السؤال')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.quizattempt', verbose_name='المحاولة')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
            },
        ),
    ]
